# Generated by Django 3.2.7 on 2021-09-25 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oglasi', '0015_alter_oglas_datum_isteka_oglasa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oglas',
            name='datum_isteka_oglasa',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 25, 19, 10, 40, 812811)),
        ),
    ]
