# Generated by Django 3.2.7 on 2021-10-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankete', '0004_auto_20210928_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitanja',
            name='tip_pitanja',
            field=models.BooleanField(default=False),
        ),
    ]
