# Generated by Django 3.2.7 on 2021-09-25 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_drzava'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ulica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='volonter',
            name='drzavljansto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.drzava'),
        ),
        migrations.AddField(
            model_name='volonter',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='drzava',
            name='naziv',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='volonter',
            name='mesto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.mesto'),
        ),
        migrations.AddField(
            model_name='volonter',
            name='ulica',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.ulica'),
        ),
        migrations.AlterField(
            model_name='organizacija',
            name='sediste',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.mesto'),
        ),
        migrations.AlterField(
            model_name='organizacija',
            name='ulica',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.ulica'),
        ),
    ]
