# Generated by Django 3.2.7 on 2021-09-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210925_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulica',
            name='naselje',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
