# Generated by Django 3.2.7 on 2021-10-05 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_ulica_naselje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesovanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='volonter',
            old_name='drzavljansto',
            new_name='drzavljanstvo',
        ),
        migrations.CreateModel(
            name='DodatniPodaci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesovanja', models.ManyToManyField(to='account.Interesovanje')),
                ('volonter', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.volonter')),
            ],
        ),
    ]
