# Generated by Django 3.2.4 on 2021-10-16 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20211005_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volonter',
            name='drzavljanstvo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.drzava'),
        ),
    ]
